# Site settings
title: Rafael Mateus - Software Developer
email: rafaelbmateus.dev@gmail.com
description: Website Rafael Mateus - Software Developer
baseurl: "/rafaelbmateus-site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://facebook.com/rafaelbmateus
github_url: https://github.com/rafaelbmateus
gitlab_url: https://gitlab.com/u/rafaelbmateus
googleplus_url: 
instagram_url: https://instagram.com/rafaelbmateus
linkedin_url: https://www.linkedin.com/in/rafaelbmateus
pinterest_url:
slack_url:
twitter_url: https://twitter.com/rafaelbmateus

# Build settings
markdown: kramdown
